#
#  开发环境
#
server:
  port: 8090
  servlet:
    context-path: /clonedata
# 文件保存目录
project:
  baseUrl: /home/zte1/clonedata/
# 日志输出目录
log:
  file:
    path: /home/zte1/clonedata/logs
# 代理IP相关配置
proxy:
  # 代理开关
  isOpenIpProxy: false
  # 打开代理后http代理比例 0-10
  proxypProportion: -1
#FTP传输封面图片 目标服务器配置
ftp:
  isopen: false
  host: 192.168.139.202
  port: 22
  username: root
  password: 123
  savepath: /home/img/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clonedata?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    initialSize: 10
    minIdle: 10
    maxActive: 30
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    throw-exception-if-no-handler-found: true #找不到conntroller抛出异常
    static-path-pattern: /static/** #静态资源

# mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    org:
      apache:
        http:
          impl:
            execchain: warn
