# -- ----------------------------
# -- clone_dict
# -- 字典
# -- ----------------------------
INSERT IGNORE INTO `clone_dict` VALUES ('1', 'maoyan_countrys_json', '{\"11\":\"德国\",\"00\":\"其他\",\"13\":\"中国台湾\",\"14\":\"俄罗斯\",\"16\":\"意大利\",\"17\":\"西班牙\",\"19\":\"波兰\",\"02\":\"大陆\",\"03\":\"美国\",\"04\":\"法国\",\"05\":\"英国\",\"06\":\" 日本 \",\"07\":\"韩国\",\"08\":\"印度\",\"09\":\"泰国\",\"20\":\"澳大利亚\",\"10\":\"中国香港\",\"21\":\"伊朗\"}', '猫眼国家转换');
INSERT IGNORE INTO `clone_dict` VALUES ('2', 'maoyan_years_json', '{\"11\":\"2016\",\"12\":\"2017\",\"13\":\"2018\",\"14\":\"2019\",\"15\":\"2020\",\"01\":\"更早\",\"02\":\" 70年代 \",\"03\":\"80年代\",\"04\":\"90年代\",\"05\":\"2000-2010\",\"06\":\"2011\",\"07\":\"2012\",\"08\":\"2013\",\"09\":\"2014\",\"10\":\"2015\"}', '猫眼年份转换');



# -- ----------------------------
# -- task_management
# -- 豆瓣电影  --  周一
# -- ----------------------------
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('33b0e4e99eec4fafa266b69770cf76dc', 'http://localhost:8090/douban/doubanMv?paramType=010201', '', '0 0 6 ? * 2', '33b0e4e99eec4fafa266b69770cf76dc', '豆瓣  电影  中国大陆  2019-2020', '1', 'http-get', '30000', '1');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('67222da9e0ef46f19d38f47c1688bd7c', 'http://localhost:8090/douban/doubanMv?paramType=010503', '', '0 20 6 ? * 2', '67222da9e0ef46f19d38f47c1688bd7c', '豆瓣  电影  中国大陆  2016-2018', '1', 'http-get', '30000', '2');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('54b03afbb34948bb8bea024827134abc', 'http://localhost:8090/douban/doubanMv?paramType=010806', '', '0 40 6 ? * 2', '54b03afbb34948bb8bea024827134abc', '豆瓣  电影  中国大陆  2013-2015', '1', 'http-get', '30000', '3');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('c67200fc74a74bfa99b042370177690e', 'http://localhost:8090/douban/doubanMv?paramType=011109', '', '0 0 7 ? * 2', 'c67200fc74a74bfa99b042370177690e', '豆瓣  电影  中国大陆  2010-2012', '1', 'http-get', '30000', '4');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('441672e3088f4ecb8f6ea6118197d21b', 'http://localhost:8090/douban/doubanMv?paramType=011312', '', '0 20 7 ? * 2', '441672e3088f4ecb8f6ea6118197d21b', '豆瓣  电影  中国大陆  2000-2009', '1', 'http-get', '30000', '5');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('d5c831a2ea42401a8056d47546f99ba8', 'http://localhost:8090/douban/doubanMv?paramType=011615', '', '0 40 7 ? * 2', 'd5c831a2ea42401a8056d47546f99ba8', '豆瓣  电影  中国大陆  1980-1999', '1', 'http-get', '30000', '6');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('f9540c26f4ed49559e73748198b05685', 'http://localhost:8090/douban/doubanMv?paramType=012219', '', '0 0 8 ? * 2', 'f9540c26f4ed49559e73748198b05685', '豆瓣  电影  中国大陆  1-1979', '1', 'http-get', '30000', '7');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('znhk1', 'http://localhost:8090/douban/doubanMv?paramType=030201', '', '0 20 8 ? * 2', 'znhk1', '豆瓣  电影  中国香港  2019-2020', '1', 'http-get', '30000', '8');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('znhk4', 'http://localhost:8090/douban/doubanMv?paramType=030503', '', '0 40 8 ? * 2', 'znhk4', '豆瓣  电影  中国香港  2016-2018', '1', 'http-get', '30000', '9');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('znhk3', 'http://localhost:8090/douban/doubanMv?paramType=030806', '', '0 0 9 ? * 2', 'znhk3', '豆瓣  电影  中国香港  2013-2015', '1', 'http-get', '30000', '10');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('znhk5', 'http://localhost:8090/douban/doubanMv?paramType=031109', '', '0 20 9 ? * 2', 'znhk5', '豆瓣  电影  中国香港  2010-2012', '1', 'http-get', '30000', '11');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('znhk2', 'http://localhost:8090/douban/doubanMv?paramType=031312', '', '0 40 9 ? * 2', 'znhk2', '豆瓣  电影  中国香港  2000-2009', '1', 'http-get', '30000', '12');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('znhk6', 'http://localhost:8090/douban/doubanMv?paramType=031615', '', '0 0 10 ? * 2', 'znhk6', '豆瓣  电影  中国香港  1980-1999', '1', 'http-get', '30000', '13');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('znhk7', 'http://localhost:8090/douban/doubanMv?paramType=032219', '', '0 20 10 ? * 2', 'znhk7', '豆瓣  电影  中国香港  1-1979', '1', 'http-get', '30000', '14');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('zntw1', 'http://localhost:8090/douban/doubanMv?paramType=040501', '', '0 40 10 ? * 2', 'zntw1', '豆瓣  电影  中国台湾  2019-2020', '1', 'http-get', '30000', '15');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('zntw4', 'http://localhost:8090/douban/doubanMv?paramType=042217', '', '0 0 11 ? * 2', 'zntw4', '豆瓣  电影  中国台湾  2016-2018', '1', 'http-get', '30000', '16');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('zntw3', 'http://localhost:8090/douban/doubanMv?paramType=041412', '', '0 20 11 ? * 2', 'zntw3', '豆瓣  电影  中国台湾  2013-2015', '1', 'http-get', '30000', '17');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('zntw2', 'http://localhost:8090/douban/doubanMv?paramType=041106', '', '0 40 11 ? * 2', 'zntw2', '豆瓣  电影  中国台湾  2000-2009', '1', 'http-get', '30000', '18');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('m1', 'http://localhost:8090/douban/doubanMv?paramType=020201', '', '0 0 12 ? * 2', 'm1', '豆瓣  电影  美国  2019-2020', '1', 'http-get', '30000', '19');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('m4', 'http://localhost:8090/douban/doubanMv?paramType=020503', '', '0 20 12 ? * 2', 'm4', '豆瓣  电影  美国  2016-2018', '1', 'http-get', '30000', '20');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('m3', 'http://localhost:8090/douban/doubanMv?paramType=020806', '', '0 40 12 ? * 2', 'm3', '豆瓣  电影  美国  2013-2015', '1', 'http-get', '30000', '21');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('m5', 'http://localhost:8090/douban/doubanMv?paramType=021109', '', '0 0 13 ? * 2', 'm5', '豆瓣  电影  美国  2010-2012', '1', 'http-get', '30000', '22');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('m2', 'http://localhost:8090/douban/doubanMv?paramType=021312', '', '0 20 13 ? * 2', 'm2', '豆瓣  电影  美国  2000-2009', '1', 'http-get', '30000', '23');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('m6', 'http://localhost:8090/douban/doubanMv?paramType=021615', '', '0 40 13 ? * 2', 'm6', '豆瓣  电影  美国  1980-1999', '1', 'http-get', '30000', '24');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('m7', 'http://localhost:8090/douban/doubanMv?paramType=022219', '', '0 0 14 ? * 2', 'm7', '豆瓣  电影  美国  1-1979', '1', 'http-get', '30000', '25');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('hgmv1', 'http://localhost:8090/douban/doubanMv?paramType=060501', '', '0 20 14 ? * 2', 'hgmv1', '豆瓣  电影  韩国  2019-2020', '1', 'http-get', '30000', '26');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('hgmv4', 'http://localhost:8090/douban/doubanMv?paramType=062217', '', '0 40 14 ? * 2', 'hgmv4', '豆瓣  电影  韩国  2016-2018', '1', 'http-get', '30000', '27');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('hgmv3', 'http://localhost:8090/douban/doubanMv?paramType=061412', '', '0 0 15 ? * 2', 'hgmv3', '豆瓣  电影  韩国  2013-2015', '1', 'http-get', '30000', '28');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('hgmv2', 'http://localhost:8090/douban/doubanMv?paramType=061106', '', '0 20 15 ? * 2', 'hgmv2', '豆瓣  电影  韩国  2000-2009', '1', 'http-get', '30000', '29');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('ygmv2', 'http://localhost:8090/douban/doubanMv?paramType=072212', '', '0 40 15 ? * 2', 'ygmv2', '豆瓣  电影  英国  1-2009', '1', 'http-get', '30000', '30');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('ygmv1', 'http://localhost:8090/douban/doubanMv?paramType=071101', '', '0 0 16 ? * 2', 'ygmv1', '豆瓣  电影  英国  2010-2020', '1', 'http-get', '30000', '31');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('rbmv1', 'http://localhost:8090/douban/doubanMv?paramType=050501', '', '0 20 16 ? * 2', 'rbmv1', '豆瓣  电影  日本  2019-2020', '1', 'http-get', '30000', '32');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('rbmv4', 'http://localhost:8090/douban/doubanMv?paramType=052217', '', '0 40 16 ? * 2', 'rbmv4', '豆瓣  电影  日本  2016-2018', '1', 'http-get', '30000', '33');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('rbmv3', 'http://localhost:8090/douban/doubanMv?paramType=051412', '', '0 0 17 ? * 2', 'rbmv3', '豆瓣  电影  日本  2013-2015', '1', 'http-get', '30000', '34');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('rbmv2', 'http://localhost:8090/douban/doubanMv?paramType=051106', '', '0 20 17 ? * 2', 'rbmv2', '豆瓣  电影  日本  2000-2009', '1', 'http-get', '30000', '35');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('xbymv2', 'http://localhost:8090/douban/doubanMv?paramType=112201', '', '0 40 17 ? * 2', 'xbymv2', '豆瓣  电影  西班牙  1-2020', '1', 'http-get', '30000', '36');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('ruidianmv2', 'http://localhost:8090/douban/doubanMv?paramType=192201', '', '0 0 18 ? * 2', 'ruidianmv2', '豆瓣  电影  瑞典  1-2020', '1', 'http-get', '30000', '37');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('aerlan2', 'http://localhost:8090/douban/doubanMv?paramType=182201', '', '0 20 18 ? * 2', 'aerlan2', '豆瓣  电影  爱尔兰  1-2020', '1', 'http-get', '30000', '38');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('aodaliyamv2', 'http://localhost:8090/douban/doubanMv?paramType=172201', '', '0 40 18 ? * 2', 'aodaliyamv2', '豆瓣  电影  澳大利亚  1-2020', '1', 'http-get', '30000', '39');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('taiguomv2', 'http://localhost:8090/douban/doubanMv?paramType=132201', '', '0 0 19 ? * 2', 'taiguomv2', '豆瓣  电影  泰国  1-2020', '1', 'http-get', '30000', '40');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('fgmv1', 'http://localhost:8090/douban/doubanMv?paramType=081101', '', '0 20 19 ? * 2', 'fgmv1', '豆瓣  电影  法国  2010-2020', '1', 'http-get', '30000', '41');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('fgmv2', 'http://localhost:8090/douban/doubanMv?paramType=082212', '', '0 40 19 ? * 2', 'fgmv2', '豆瓣  电影  法国  1-2009', '1', 'http-get', '30000', '42');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('ydlmv2', 'http://localhost:8090/douban/doubanMv?paramType=102201', '', '0 0 20 ? * 2', 'ydlmv2', '豆瓣  电影  意大利  1-2020', '1', 'http-get', '30000', '43');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('dgmv1', 'http://localhost:8090/douban/doubanMv?paramType=091101', '', '0 20 20 ? * 2', 'dgmv1', '豆瓣  电影  德国  2010-2020', '1', 'http-get', '30000', '44');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('dgmv2', 'http://localhost:8090/douban/doubanMv?paramType=092212', '', '0 40 20 ? * 2', 'dgmv2', '豆瓣  电影  德国  1-2009', '1', 'http-get', '30000', '45');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('baximv2', 'http://localhost:8090/douban/doubanMv?paramType=202201', '', '0 0 21 ? * 2', 'baximv2', '豆瓣  电影  巴西  1-2020', '1', 'http-get', '30000', '46');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('yindumv1', 'http://localhost:8090/douban/doubanMv?paramType=121101', '', '0 20 21 ? * 2', 'yindumv1', '豆瓣  电影  印度  2010-2020', '1', 'http-get', '30000', '47');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('yindumv2', 'http://localhost:8090/douban/doubanMv?paramType=122212', '', '0 40 21 ? * 2', 'yindumv2', '豆瓣  电影  印度  1-2009', '1', 'http-get', '30000', '48');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('jianadamv2', 'http://localhost:8090/douban/doubanMv?paramType=162201', '', '0 0 22 ? * 2', 'jianadamv2', '豆瓣  电影  加拿大  1-2020', '1', 'http-get', '30000', '49');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('eluosimv2', 'http://localhost:8090/douban/doubanMv?paramType=142201', '', '0 20 22 ? * 2', 'eluosimv2', '豆瓣  电影  俄罗斯  1-2020', '1', 'http-get', '30000', '50');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('danmaimv2', 'http://localhost:8090/douban/doubanMv?paramType=212201', '', '0 40 22 ? * 2', 'danmaimv2', '豆瓣  电影  丹麦  1-2020', '1', 'http-get', '30000', '51');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('yilangmv2', 'http://localhost:8090/douban/doubanMv?paramType=152201', '', '0 0 23 ? * 2', 'yilangmv2', '豆瓣  电影  伊朗  1-2020', '1', 'http-get', '30000', '52');
# -- ----------------------------
# -- task_management
# -- 豆瓣电视剧  --  周三
# -- ----------------------------
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-CN-01', 'http://localhost:8090/douban/doubanTv?paramType=010201', '', '0 0 6 ? * 4', 'douban-tv-CN-01', '豆瓣  电视剧  中国大陆  2019-2020', '1', 'http-get', '30000', '101');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-CN-02', 'http://localhost:8090/douban/doubanTv?paramType=010503', '', '0 20 6 ? * 4', 'douban-tv-CN-02', '豆瓣  电视剧  中国大陆  2016-2018', '1', 'http-get', '30000', '102');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-CN-03', 'http://localhost:8090/douban/doubanTv?paramType=010806', '', '0 40 6 ? * 4', 'douban-tv-CN-03', '豆瓣  电视剧  中国大陆  2013-2015', '1', 'http-get', '30000', '103');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-CN-04', 'http://localhost:8090/douban/doubanTv?paramType=011109', '', '0 0 7 ? * 4', 'douban-tv-CN-04', '豆瓣  电视剧  中国大陆  2010-2012', '1', 'http-get', '30000', '104');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-CN-05', 'http://localhost:8090/douban/doubanTv?paramType=011312', '', '0 20 7 ? * 4', 'douban-tv-CN-05', '豆瓣  电视剧  中国大陆  2000-2009', '1', 'http-get', '30000', '105');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-CN-06', 'http://localhost:8090/douban/doubanTv?paramType=011615', '', '0 40 7 ? * 4', 'douban-tv-CN-06', '豆瓣  电视剧  中国大陆  1980-1999', '1', 'http-get', '30000', '106');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-CN-07', 'http://localhost:8090/douban/doubanTv?paramType=012219', '', '0 0 8 ? * 4', 'douban-tv-CN-07', '豆瓣  电视剧  中国大陆  1-1979', '1', 'http-get', '30000', '107');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-HK-01', 'http://localhost:8090/douban/doubanTv?paramType=030201', '', '0 20 8 ? * 4', 'douban-tv-HK-01', '豆瓣  电视剧  中国香港  2019-2020', '1', 'http-get', '30000', '108');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-HK-02', 'http://localhost:8090/douban/doubanTv?paramType=030503', '', '0 40 8 ? * 4', 'douban-tv-HK-02', '豆瓣  电视剧  中国香港  2016-2018', '1', 'http-get', '30000', '109');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-HK-03', 'http://localhost:8090/douban/doubanTv?paramType=030806', '', '0 0 9 ? * 4', 'douban-tv-HK-03', '豆瓣  电视剧  中国香港  2013-2015', '1', 'http-get', '30000', '110');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-HK-04', 'http://localhost:8090/douban/doubanTv?paramType=031109', '', '0 20 9 ? * 4', 'douban-tv-HK-04', '豆瓣  电视剧  中国香港  2010-2012', '1', 'http-get', '30000', '111');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-HK-05', 'http://localhost:8090/douban/doubanTv?paramType=031312', '', '0 40 9 ? * 4', 'douban-tv-HK-05', '豆瓣  电视剧  中国香港  2000-2009', '1', 'http-get', '30000', '112');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-HK-06', 'http://localhost:8090/douban/doubanTv?paramType=031615', '', '0 0 10 ? * 4', 'douban-tv-HK-06', '豆瓣  电视剧  中国香港  1980-1999', '1', 'http-get', '30000', '113');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-HK-07', 'http://localhost:8090/douban/doubanTv?paramType=032219', '', '0 20 10 ? * 4', 'douban-tv-HK-07', '豆瓣  电视剧  中国香港  1-1979', '1', 'http-get', '30000', '114');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-TW-01', 'http://localhost:8090/douban/doubanTv?paramType=040501', '', '0 40 10 ? * 4', 'douban-tv-TW-01', '豆瓣  电视剧  中国台湾  2019-2020', '1', 'http-get', '30000', '115');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-TW-02', 'http://localhost:8090/douban/doubanTv?paramType=042217', '', '0 0 11 ? * 4', 'douban-tv-TW-02', '豆瓣  电视剧  中国台湾  2016-2018', '1', 'http-get', '30000', '116');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-TW-03', 'http://localhost:8090/douban/doubanTv?paramType=041412', '', '0 20 11 ? * 4', 'douban-tv-TW-03', '豆瓣  电视剧  中国台湾  2013-2015', '1', 'http-get', '30000', '117');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-TW-04', 'http://localhost:8090/douban/doubanTv?paramType=041106', '', '0 40 11 ? * 4', 'douban-tv-TW-04', '豆瓣  电视剧  中国台湾  2000-2009', '1', 'http-get', '30000', '118');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-m1', 'http://localhost:8090/douban/doubanTv?paramType=020201', '', '0 0 12 ? * 4', 'douban-tv-m1', '豆瓣  电视剧  美国  2019-2020', '1', 'http-get', '30000', '119');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-m4', 'http://localhost:8090/douban/doubanTv?paramType=020503', '', '0 20 12 ? * 4', 'douban-tv-m4', '豆瓣  电视剧  美国  2016-2018', '1', 'http-get', '30000', '120');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-m3', 'http://localhost:8090/douban/doubanTv?paramType=020806', '', '0 40 12 ? * 4', 'douban-tv-m3', '豆瓣  电视剧  美国  2013-2015', '1', 'http-get', '30000', '121');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-m5', 'http://localhost:8090/douban/doubanTv?paramType=021109', '', '0 0 13 ? * 4', 'douban-tv-m5', '豆瓣  电视剧  美国  2010-2012', '1', 'http-get', '30000', '122');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-m2', 'http://localhost:8090/douban/doubanTv?paramType=021312', '', '0 20 13 ? * 4', 'douban-tv-m2', '豆瓣  电视剧  美国  2000-2009', '1', 'http-get', '30000', '123');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-m6', 'http://localhost:8090/douban/doubanTv?paramType=021615', '', '0 40 13 ? * 4', 'douban-tv-m6', '豆瓣  电视剧  美国  1980-1999', '1', 'http-get', '30000', '124');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-m7', 'http://localhost:8090/douban/doubanTv?paramType=022219', '', '0 0 14 ? * 4', 'douban-tv-m7', '豆瓣  电视剧  美国  1-1979', '1', 'http-get', '30000', '125');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-hgmv1', 'http://localhost:8090/douban/doubanTv?paramType=060501', '', '0 20 14 ? * 4', 'douban-tv-hgmv1', '豆瓣  电视剧  韩国  2019-2020', '1', 'http-get', '30000', '126');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-hgmv4', 'http://localhost:8090/douban/doubanTv?paramType=062217', '', '0 40 14 ? * 4', 'douban-tv-hgmv4', '豆瓣  电视剧  韩国  2016-2018', '1', 'http-get', '30000', '127');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-hgmv3', 'http://localhost:8090/douban/doubanTv?paramType=061412', '', '0 0 15 ? * 4', 'douban-tv-hgmv3', '豆瓣  电视剧  韩国  2013-2015', '1', 'http-get', '30000', '128');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-hgmv2', 'http://localhost:8090/douban/doubanTv?paramType=061106', '', '0 20 15 ? * 4', 'douban-tv-hgmv2', '豆瓣  电视剧  韩国  2000-2009', '1', 'http-get', '30000', '129');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-ygmv2', 'http://localhost:8090/douban/doubanTv?paramType=072212', '', '0 40 15 ? * 4', 'douban-tv-ygmv2', '豆瓣  电视剧  英国  1-2009', '1', 'http-get', '30000', '130');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-ygmv1', 'http://localhost:8090/douban/doubanTv?paramType=071101', '', '0 0 16 ? * 4', 'douban-tv-ygmv1', '豆瓣  电视剧  英国  2010-2020', '1', 'http-get', '30000', '131');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-rbmv1', 'http://localhost:8090/douban/doubanTv?paramType=050501', '', '0 20 16 ? * 4', 'douban-tv-rbmv1', '豆瓣  电视剧  日本  2019-2020', '1', 'http-get', '30000', '132');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-rbmv4', 'http://localhost:8090/douban/doubanTv?paramType=052217', '', '0 40 16 ? * 4', 'douban-tv-rbmv4', '豆瓣  电视剧  日本  2016-2018', '1', 'http-get', '30000', '133');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-rbmv3', 'http://localhost:8090/douban/doubanTv?paramType=051412', '', '0 0 17 ? * 4', 'douban-tv-rbmv3', '豆瓣  电视剧  日本  2013-2015', '1', 'http-get', '30000', '134');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-rbmv2', 'http://localhost:8090/douban/doubanTv?paramType=051106', '', '0 20 17 ? * 4', 'douban-tv-rbmv2', '豆瓣  电视剧  日本  2000-2009', '1', 'http-get', '30000', '135');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-xbymv2', 'http://localhost:8090/douban/doubanTv?paramType=112201', '', '0 40 17 ? * 4', 'douban-tv-xbymv2', '豆瓣  电视剧  西班牙  1-2020', '1', 'http-get', '30000', '136');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-ruidianmv2', 'http://localhost:8090/douban/doubanTv?paramType=192201', '', '0 0 18 ? * 4', 'douban-tv-ruidianmv2', '豆瓣  电视剧  瑞典  1-2020', '1', 'http-get', '30000', '137');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-aerlan2', 'http://localhost:8090/douban/doubanTv?paramType=182201', '', '0 20 18 ? * 4', 'douban-tv-aerlan2', '豆瓣  电视剧  爱尔兰  1-2020', '1', 'http-get', '30000', '138');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-aodaliyamv2', 'http://localhost:8090/douban/doubanTv?paramType=172201', '', '0 40 18 ? * 4', 'douban-tv-aodaliyamv2', '豆瓣  电视剧  澳大利亚  1-2020', '1', 'http-get', '30000', '139');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-taiguomv2', 'http://localhost:8090/douban/doubanTv?paramType=132201', '', '0 0 19 ? * 4', 'douban-tv-taiguomv2', '豆瓣  电视剧  泰国  1-2020', '1', 'http-get', '30000', '140');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-fgmv1', 'http://localhost:8090/douban/doubanTv?paramType=081101', '', '0 20 19 ? * 4', 'douban-tv-fgmv1', '豆瓣  电视剧  法国  2010-2020', '1', 'http-get', '30000', '141');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-fgmv2', 'http://localhost:8090/douban/doubanTv?paramType=082212', '', '0 40 19 ? * 4', 'douban-tv-fgmv2', '豆瓣  电视剧  法国  1-2009', '1', 'http-get', '30000', '142');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-ydlmv2', 'http://localhost:8090/douban/doubanTv?paramType=102201', '', '0 0 20 ? * 4', 'douban-tv-ydlmv2', '豆瓣  电视剧  意大利  1-2020', '1', 'http-get', '30000', '143');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-dgmv1', 'http://localhost:8090/douban/doubanTv?paramType=091101', '', '0 20 20 ? * 4', 'douban-tv-dgmv1', '豆瓣  电视剧  德国  2010-2020', '1', 'http-get', '30000', '144');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-dgmv2', 'http://localhost:8090/douban/doubanTv?paramType=092212', '', '0 40 20 ? * 4', 'douban-tv-dgmv2', '豆瓣  电视剧  德国  1-2009', '1', 'http-get', '30000', '145');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-baximv2', 'http://localhost:8090/douban/doubanTv?paramType=202201', '', '0 0 21 ? * 4', 'douban-tv-baximv2', '豆瓣  电视剧  巴西  1-2020', '1', 'http-get', '30000', '146');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-yindumv1', 'http://localhost:8090/douban/doubanTv?paramType=121101', '', '0 20 21 ? * 4', 'douban-tv-yindumv1', '豆瓣  电视剧  印度  2010-2020', '1', 'http-get', '30000', '147');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-yindumv2', 'http://localhost:8090/douban/doubanTv?paramType=122212', '', '0 40 21 ? * 4', 'douban-tv-yindumv2', '豆瓣  电视剧  印度  1-2009', '1', 'http-get', '30000', '148');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-jianadamv2', 'http://localhost:8090/douban/doubanTv?paramType=162201', '', '0 0 22 ? * 4', 'douban-tv-jianadamv2', '豆瓣  电视剧  加拿大  1-2020', '1', 'http-get', '30000', '149');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-eluosimv2', 'http://localhost:8090/douban/doubanTv?paramType=142201', '', '0 20 22 ? * 4', 'douban-tv-eluosimv2', '豆瓣  电视剧  俄罗斯  1-2020', '1', 'http-get', '30000', '150');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-danmaimv2', 'http://localhost:8090/douban/doubanTv?paramType=212201', '', '0 40 22 ? * 4', 'douban-tv-danmaimv2', '豆瓣  电视剧  丹麦  1-2020', '1', 'http-get', '30000', '151');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('douban-tv-yilangmv2', 'http://localhost:8090/douban/doubanTv?paramType=152201', '', '0 0 23 ? * 4', 'douban-tv-yilangmv2', '豆瓣  电视剧  伊朗  1-2020', '1', 'http-get', '30000', '152');
# -- ----------------------------
# -- task_management
# -- 豆瓣电影电视剧补充  --  周五
# -- ----------------------------
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-CN-01', 'http://localhost:8090/douban/doubanMv?paramType=010201', '', '0 0 6 ? * 6', 're-douban-mv-CN-01', '豆瓣  电影  中国大陆  2019-2020', '1', 'http-get', '30000', '201');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-CN-02', 'http://localhost:8090/douban/doubanMv?paramType=010503', '', '0 20 6 ? * 6', 're-douban-mv-CN-02', '豆瓣  电影  中国大陆  2016-2018', '1', 'http-get', '30000', '202');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-CN-03', 'http://localhost:8090/douban/doubanMv?paramType=010806', '', '0 40 6 ? * 6', 're-douban-mv-CN-03', '豆瓣  电影  中国大陆  2013-2015', '1', 'http-get', '30000', '203');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-CN-04', 'http://localhost:8090/douban/doubanMv?paramType=011109', '', '0 0 7 ? * 6', 're-douban-mv-CN-04', '豆瓣  电影  中国大陆  2010-2012', '1', 'http-get', '30000', '204');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-CN-05', 'http://localhost:8090/douban/doubanMv?paramType=011312', '', '0 20 7 ? * 6', 're-douban-mv-CN-05', '豆瓣  电影  中国大陆  2000-2009', '1', 'http-get', '30000', '205');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-CN-06', 'http://localhost:8090/douban/doubanMv?paramType=011615', '', '0 40 7 ? * 6', 're-douban-mv-CN-06', '豆瓣  电影  中国大陆  1980-1999', '1', 'http-get', '30000', '206');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-CN-07', 'http://localhost:8090/douban/doubanMv?paramType=012219', '', '0 0 8 ? * 6', 're-douban-mv-CN-07', '豆瓣  电影  中国大陆  1-1979', '1', 'http-get', '30000', '207');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-HK-01', 'http://localhost:8090/douban/doubanMv?paramType=030201', '', '0 20 8 ? * 6', 're-douban-mv-HK-01', '豆瓣  电影  中国香港  2019-2020', '1', 'http-get', '30000', '208');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-HK-02', 'http://localhost:8090/douban/doubanMv?paramType=030503', '', '0 40 8 ? * 6', 're-douban-mv-HK-02', '豆瓣  电影  中国香港  2016-2018', '1', 'http-get', '30000', '209');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-HK-03', 'http://localhost:8090/douban/doubanMv?paramType=030806', '', '0 0 9 ? * 6', 're-douban-mv-HK-03', '豆瓣  电影  中国香港  2013-2015', '1', 'http-get', '30000', '210');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-HK-04', 'http://localhost:8090/douban/doubanMv?paramType=031109', '', '0 20 9 ? * 6', 're-douban-mv-HK-04', '豆瓣  电影  中国香港  2010-2012', '1', 'http-get', '30000', '211');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-HK-05', 'http://localhost:8090/douban/doubanMv?paramType=031312', '', '0 40 9 ? * 6', 're-douban-mv-HK-05', '豆瓣  电影  中国香港  2000-2009', '1', 'http-get', '30000', '212');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-HK-06', 'http://localhost:8090/douban/doubanMv?paramType=031615', '', '0 0 10 ? * 6', 're-douban-mv-HK-06', '豆瓣  电影  中国香港  1980-1999', '1', 'http-get', '30000', '213');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-HK-07', 'http://localhost:8090/douban/doubanMv?paramType=032219', '', '0 20 10 ? * 6', 're-douban-mv-HK-07', '豆瓣  电影  中国香港  1-1979', '1', 'http-get', '30000', '214');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-M-01', 'http://localhost:8090/douban/doubanMv?paramType=020201', '', '0 0 12 ? * 6', 're-douban-mv-M-01', '豆瓣  电影  美国  2019-2020', '1', 'http-get', '30000', '219');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-M-02', 'http://localhost:8090/douban/doubanMv?paramType=020503', '', '0 20 12 ? * 6', 're-douban-mv-M-02', '豆瓣  电影  美国  2016-2018', '1', 'http-get', '30000', '220');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-M-03', 'http://localhost:8090/douban/doubanMv?paramType=020806', '', '0 40 12 ? * 6', 're-douban-mv-M-03', '豆瓣  电影  美国  2013-2015', '1', 'http-get', '30000', '221');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-M-04', 'http://localhost:8090/douban/doubanMv?paramType=021109', '', '0 0 13 ? * 6', 're-douban-mv-M-04', '豆瓣  电影  美国  2010-2012', '1', 'http-get', '30000', '222');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-M-05', 'http://localhost:8090/douban/doubanMv?paramType=021312', '', '0 20 13 ? * 6', 're-douban-mv-M-05', '豆瓣  电影  美国  2000-2009', '1', 'http-get', '30000', '223');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-M-06', 'http://localhost:8090/douban/doubanMv?paramType=021615', '', '0 40 13 ? * 6', 're-douban-mv-M-06', '豆瓣  电影  美国  1980-1999', '1', 'http-get', '30000', '224');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-mv-M-07', 'http://localhost:8090/douban/doubanMv?paramType=022219', '', '0 0 14 ? * 6', 're-douban-mv-M-07', '豆瓣  电影  美国  1-1979', '1', 'http-get', '30000', '225');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-CN-01', 'http://localhost:8090/douban/doubanTv?paramType=010201', '', '0 0 6 ? * 6', 're-douban-tv-CN-01', '豆瓣  电视剧  中国大陆  2019-2020', '1', 'http-get', '30000', '226');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-CN-02', 'http://localhost:8090/douban/doubanTv?paramType=010503', '', '0 20 6 ? * 6', 're-douban-tv-CN-02', '豆瓣  电视剧  中国大陆  2016-2018', '1', 'http-get', '30000', '227');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-CN-03', 'http://localhost:8090/douban/doubanTv?paramType=010806', '', '0 40 6 ? * 6', 're-douban-tv-CN-03', '豆瓣  电视剧  中国大陆  2013-2015', '1', 'http-get', '30000', '228');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-CN-04', 'http://localhost:8090/douban/doubanTv?paramType=011109', '', '0 0 7 ? * 6', 're-douban-tv-CN-04', '豆瓣  电视剧  中国大陆  2010-2012', '1', 'http-get', '30000', '229');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-CN-05', 'http://localhost:8090/douban/doubanTv?paramType=011312', '', '0 20 7 ? * 6', 're-douban-tv-CN-05', '豆瓣  电视剧  中国大陆  2000-2009', '1', 'http-get', '30000', '230');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-CN-06', 'http://localhost:8090/douban/doubanTv?paramType=011615', '', '0 40 7 ? * 6', 're-douban-tv-CN-06', '豆瓣  电视剧  中国大陆  1980-1999', '1', 'http-get', '30000', '231');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-CN-07', 'http://localhost:8090/douban/doubanTv?paramType=012219', '', '0 0 8 ? * 6', 're-douban-tv-CN-07', '豆瓣  电视剧  中国大陆  1-1979', '1', 'http-get', '30000', '232');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-m1', 'http://localhost:8090/douban/doubanTv?paramType=020201', '', '0 0 12 ? * 6', 're-douban-tv-m1', '豆瓣  电视剧  美国  2019-2020', '1', 'http-get', '30000', '233');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-m4', 'http://localhost:8090/douban/doubanTv?paramType=020503', '', '0 20 12 ? * 6', 're-douban-tv-m4', '豆瓣  电视剧  美国  2016-2018', '1', 'http-get', '30000', '234');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-m3', 'http://localhost:8090/douban/doubanTv?paramType=020806', '', '0 40 12 ? * 6', 're-douban-tv-m3', '豆瓣  电视剧  美国  2013-2015', '1', 'http-get', '30000', '235');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-m5', 'http://localhost:8090/douban/doubanTv?paramType=021109', '', '0 0 13 ? * 6', 're-douban-tv-m5', '豆瓣  电视剧  美国  2010-2012', '1', 'http-get', '30000', '236');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-m2', 'http://localhost:8090/douban/doubanTv?paramType=021312', '', '0 20 13 ? * 6', 're-douban-tv-m2', '豆瓣  电视剧  美国  2000-2009', '1', 'http-get', '30000', '237');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-m6', 'http://localhost:8090/douban/doubanTv?paramType=021615', '', '0 40 13 ? * 6', 're-douban-tv-m6', '豆瓣  电视剧  美国  1980-1999', '1', 'http-get', '30000', '238');
INSERT IGNORE INTO `testa`.`task_management` (`id`, `excute_target`, `external_code`, `task_excute_plan`, `task_id`, `task_name`, `task_status`, `task_type`, `timeout_second`, `cre_dt`) VALUES ('re-douban-tv-m7', 'http://localhost:8090/douban/doubanTv?paramType=022219', '', '0 0 14 ? * 6', 're-douban-tv-m7', '豆瓣  电视剧  美国  1-1979', '1', 'http-get', '30000', '239');
